export const NOTIFICATION_TYPES = {
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  DOCUMENT_PENDING: 'DOCUMENT_PENDING',
  DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_COMMENT: 'TICKET_COMMENT',
  TICKET_RESOLVED: 'TICKET_RESOLVED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_MOVED: 'TASK_MOVED',
  TASK_COMMENT: 'TASK_COMMENT',
  TASK_DUE_SOON: 'TASK_DUE_SOON',
  MEETING_CREATED: 'MEETING_CREATED',
  MEETING_RESCHEDULED: 'MEETING_RESCHEDULED',
  MEETING_CANCELLED: 'MEETING_CANCELLED',
  MEETING_REMINDER: 'MEETING_REMINDER',
  REQUEST_CREATED: 'REQUEST_CREATED',
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  REQUEST_RESOLVED: 'REQUEST_RESOLVED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_CLOSED: 'REQUEST_CLOSED',
  INVENTORY_LOW_STOCK: 'INVENTORY_LOW_STOCK',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  SYSTEM: 'SYSTEM',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const NOTIFICATION_RESOURCE_TYPES = {
  ANNOUNCEMENT: 'announcement',
  DOCUMENT: 'document',
  FOLDER: 'folder',
  TICKET: 'ticket',
  TASK: 'task',
  BOARD: 'board',
  MEETING: 'meeting',
  REQUEST: 'request',
  ASSET: 'asset',
  CONSUMABLE: 'consumable',
  INVENTORY: 'inventory',
  CHAT: 'chat',
} as const;

export type NotificationResourceType =
  (typeof NOTIFICATION_RESOURCE_TYPES)[keyof typeof NOTIFICATION_RESOURCE_TYPES];
