export const TASK_ACTIVITY_ACTIONS = {
  CREATED: 'CREATED',
  MOVED: 'MOVED',
  ASSIGNED: 'ASSIGNED',
  COMMENTED: 'COMMENTED',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  ARCHIVED: 'ARCHIVED',
  UPDATED: 'UPDATED',
} as const;

export type TaskActivityAction = (typeof TASK_ACTIVITY_ACTIONS)[keyof typeof TASK_ACTIVITY_ACTIONS];
